openapi: 3.0.3
info: 
  title: Revision API
  version: 1.0.0
servers:
    - url: http://localhost
paths:
  /books:
    get:
      summary: get all books
      description: return the books order by author
      operationId: getBooks
      parameters:
        - in: query
          name: book name
          description: Filter hte return books by given name
          required: false
          schema:
            type: string
      responses:
        200:
          description: The returned books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    put:
      summary: Create or update the list of books
      operationId: updateBook
      requestBody:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
      responses:
        200:
          description: list of the modified list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

components:
  schemas:
    CreateBook:
      type: object
      properties:
        bookName:
          type: string
          example: Le Petit Prince
        author:
          type: string
        releaseDate:
          type: string
          format: date
        topic:
          $ref: '#/components/schemas/Topic'
    Book:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateBook'
      properties:
        id:
          type: string
    Topic:
      type: string
      enum:
        - ROMANCE
        - COMEDY
        - ADVENTURE
        - OTHER